### ISSUE TITLE
Assertion error on deletion of negative map-cache entry

### ISSUE THREAD

**Issue by m01** [OpenOverlayRouter/oor#12] opened 2017-07-25 22:27 UTC
Setup:
* OOR latest master (ee707f1)
* OOR in xTR mode on [Ubiquiti EdgeRouter Lite](https://me.m01.eu/blog/2017/07/lisp-on-ubiquiti-edgerouter-lite) on beta network - I appreciate this is not a "supported" platform, but I thought to document this in case there's anything to be learned from this anyway (other than this bug OOR does seem to work).
* 1 laptop with IP address from EID prefix for testing, sitting mostly idle

It looks like OOR sends a Map-Request for a DNS packet (must be the first excluding initial SMRs), gets back a negative map-reply, and then 6mins later when it expires asserts because the map-cache entry doesn't exist.

```
[2017/7/16 19:46:36] INFO:

 Open Overlay Router (v1.1.1): started...

...
[2017/7/16 19:46:38] DEBUG: Map-Request-> flags:a=0,m=0,p=0,s=0,P=0,S=0, irc: 0 (+1), record-count: 1, nonce: <nonce>, itr-rlocs: <my RLOC>, src-eid: <my EID>, req-eid: 8.8.4.4/32
[2017/7/16 19:46:38] DEBUG: ECM -> flags:s, inner IP: <my EID> -> 8.8.4.4/32, inner UDP: 4342 -> 4342
[2017/7/16 19:46:38] DEBUG: Sent control message IP: <my RLOC>-> 217.8.98.42 UDP: 4342 -> 4342
[2017/7/16 19:46:38] DEBUG: Received Map-Reply-> flags:P=0,E=0,S=0, record-count: 1, nonce: <nonce>, IP: 217.8.98.42 -> <my RLOC>, UDP: 4342 -> 4342
[2017/7/16 19:46:38] DEBUG:   Mapping-record -> ttl: 6 loc-count: 0 action: native-forward auth: 1 map-version: 0 eid: 0.0.0.0/3
[2017/7/16 19:46:38] DEBUG: Balancing locator vector for 0.0.0.0/3:
[2017/7/16 19:46:38] DEBUG:   IPv4 locators vector (0 locators):
[2017/7/16 19:46:38] DEBUG:   IPv6 locators vector (0 locators):
[2017/7/16 19:46:38] DEBUG:   IPv4 & IPv6 locators vector (0 locators):
[2017/7/16 19:46:38] DEBUG: The map cache entry of EID 0.0.0.0/3 will expire in 6 minutes.
...
[2017/7/16 19:52:36] DEBUG:  Successfully probed RLOC 193.162.145.46 of cache entry with EID ::/0
[2017/7/16 19:52:37] DEBUG: Got expiration for EID 0.0.0.0/3
[2017/7/16 19:52:37] DEBUG: Got expiration for EID 0.0.0.0/3
oor: lib/map_cache_entry.c:64: mcache_entry_del: Assertion `entry' failed.
Aborted
```

I did see the following two ERRors, but not sure if they are related, they look like transient failures?

```
[2017/7/16 19:47:37] DEBUG: Sending Map-Reply-> flags:P=1,E=0,S=0, record-count: 1, nonce: NNNN
[2017/7/16 19:47:37] DEBUG: Sent control message IP: <my RLOC> -> 193.162.145.46 UDP: 4342 -> 4342
[2017/7/16 19:47:45] ERR: LMAPI: Error while ZMQ receiving: Resource temporarily unavailable

[2017/7/16 19:47:45] ERR: oor_api_loop: Error while trying to retrieve API packet

[2017/7/16 19:47:47] DEBUG: Got expiration for EID 32.0.0.0/6
[2017/7/16 19:47:51] DEBUG: No map cache for EID <some IP>. Sending Map-Request!
```

**Comment by m01** [comment] 2017-07-29 19:13
I had a look with gdb to see if I can find any more useful info.
Stack trace:
```
(gdb) bt
#0  0x77ba5b48 in raise () from /lib/mips-linux-gnu/libc.so.6
#1  0x77baab14 in abort () from /lib/mips-linux-gnu/libc.so.6
#2  0x77b9d6c0 in __assert_fail () from /lib/mips-linux-gnu/libc.so.6
#3  0x0044bc18 in mcache_entry_del (entry=0x0) at lib/map_cache_entry.c:64
#4  0x00416ad4 in tr_mcache_remove_entry (xtr=0x4931e8, mce=0x4918e8)
    at control/lisp_xtr.c:1862
#5  0x00410404 in mc_entry_expiration_timer_cb (timer=0x491988)
    at control/lisp_xtr.c:126
#6  0x00458738 in handle_timers () at lib/timers.c:362
#7  0x00458808 in process_timer_signal (sl=0x487c20) at lib/timers.c:384
#8  0x00454854 in sock_process_fd (lst=0x487c68, fdset=0x487c78)
    at lib/sockets.c:245
#9  0x00454978 in sockmstr_process_all (m=0x487c68) at lib/sockets.c:271
#10 0x0045fc84 in main (argc=3, argv=0x7fdffc84) at oor.c:500
```

The EID being deleted in [tr_mcache_remove_entry @ lisp_xtr:1862](https://github.com/OpenOverlayRouter/oor/blob/ee707f185be5130d726d6ca4d3b5fcaa41e11eba/oor/control/lisp_xtr.c#L1862):
```
(gdb) p eid
$1 = (struct _lisp_addr_t *) 0x491890
(gdb) p *eid
$2 = {{{ip = {afi = 2, addr = {v4 = {s_addr = 0}, v6 = {__in6_u = {
              __u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0,
                0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}}}, ippref = {
        prefix = {afi = 2, addr = {v4 = {s_addr = 0}, v6 = {__in6_u = {
                __u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0,
                  0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}}},
        plen = 3 '\003'}, lcaf = {type = LCAF_IID, addr = 0x0}},
    lafi = LM_AFI_IPPREF}}
(gdb) p data
$3 = (void *) 0x0
```

**Comment by albert-lopez** [comment] 2017-07-31 07:49
Thank you Michiel for your fantastic guide in how to compile OOR into Ubiquiti EdgeRouter. When we have a moment we will put a link in the wiki.
Have you tried if this error is still appearing with the new release of last week? I tried to reproduce it an I was not able to do it.

**Comment by m01** [comment] 2017-08-05 12:28
Hi Albert,
Thank you, I'll try the latest version and let you know.

**Comment by neutronscott** [comment] 2018-01-13 18:44
I believe I have the same issue using OOR 1.2.0. I compiled from source for OpenWRT/LEDE 17.01.4 and also used Debian 9 package with same result. I am not yet well read in LISP, but it seems I get two expirations because I put in both map servers, and the second attempt to delete fails assertion. 

From Debian 9 system:
```
[2018/1/11 7:44:36] DEBUG: Got expiration for EID 136.0.0.0/5
[2018/1/11 7:44:36] DEBUG-3: tun_rm_fwd_from_entry: Removing all the forwading entries association with the EID 136.0.0.0/5
[2018/1/11 7:44:36] DEBUG-3: ttable_remove: Remove tupla: Src_addr: 153.16.29.177, Dst addr: 141.212.122.81, Proto: TCP, Src Port: 443, Dst Port: 10850
IID|VNI: 0

[2018/1/11 7:44:36] DEBUG-3: pt_remove_ip_addr: removing entry with key: 136.0.0.0/5
[2018/1/11 7:44:36] DEBUG-3: **************** LISP Mapping Cache ******************

[2018/1/11 7:44:36] DEBUG-3: ENTRY UPTIME: 19:06:18, EXPIRES: 19:02:42, TYPE: Dynamic, ACTIVE: Yes
EID: 216.0.0.0/8, ttl: 9, loc-count: 0, action: native-forward, auth: 1


[2018/1/11 7:44:36] DEBUG-3: *******************************************************

[2018/1/11 7:44:36] DEBUG: Got expiration for EID 136.0.0.0/5
[2018/1/11 7:44:36] DEBUG-3: tun_rm_fwd_from_entry: Removing all the forwading entries association with the EID 136.0.0.0/5
[2018/1/11 7:44:36] DEBUG: tun_rm_fwd_from_entry: Entry 136.0.0.0/5 not found in the shasht!
[2018/1/11 7:44:36] DEBUG-3: pt_remove_ip_addr: Unable to locate cache entry 136.0.0.0/5 for deletion
oor: lib/map_cache_entry.c:64: mcache_entry_del: Assertion `entry' failed.
Aborted
```

Later on OpenWRT:
```
[2018/1/13 0:0:43] DEBUG: Got expiration for EID 136.0.0.0/5
[2018/1/13 0:0:43] DEBUG-3: tun_rm_fwd_from_entry: Removing all the forwading entries association with the EID 136.0.0.0/5
[2018/1/13 0:0:43] DEBUG: tun_rm_fwd_from_entry: Entry 136.0.0.0/5 not found in the shasht!
[2018/1/13 0:0:43] DEBUG-3: pt_remove_ip_addr: removing entry with key: 136.0.0.0/5
[2018/1/13 0:0:43] DEBUG-3: **************** LISP Mapping Cache ******************

[2018/1/13 0:0:43] DEBUG-3: ENTRY UPTIME: 00:04:49, EXPIRES: 00:05:11, TYPE: Dynamic, ACTIVE: Yes
EID: 64.0.0.0/4, ttl: 10, loc-count: 0, action: native-forward, auth: 1


[2018/1/13 0:0:43] DEBUG-3: ENTRY UPTIME: 00:02:16, EXPIRES: 00:04:44, TYPE: Dynamic, ACTIVE: Yes
EID: 88.0.0.0/5, ttl: 7, loc-count: 0, action: native-forward, auth: 1


[2018/1/13 0:0:43] DEBUG-3: ENTRY UPTIME: 00:08:52, EXPIRES: 00:05:08, TYPE: Dynamic, ACTIVE: Yes
EID: 96.0.0.0/3, ttl: 14, loc-count: 0, action: native-forward, auth: 1


[2018/1/13 0:0:43] DEBUG-3: ENTRY UPTIME: 00:04:04, EXPIRES: 00:10:56, TYPE: Dynamic, ACTIVE: Yes
EID: 160.0.0.0/3, ttl: 15, loc-count: 0, action: native-forward, auth: 1


[2018/1/13 0:0:43] DEBUG-3: ENTRY UPTIME: 00:02:46, EXPIRES: 00:11:14, TYPE: Dynamic, ACTIVE: Yes
EID: 196.0.0.0/7, ttl: 14, loc-count: 0, action: native-forward, auth: 1


[2018/1/13 0:0:43] DEBUG-3: ENTRY UPTIME: 00:01:34, EXPIRES: 00:00:26, TYPE: Dynamic, ACTIVE: Yes
EID: 200.0.0.0/6, ttl: 2, loc-count: 0, action: native-forward, auth: 1


[2018/1/13 0:0:43] DEBUG-3: *******************************************************

[2018/1/13 0:0:43] DEBUG: Got expiration for EID 136.0.0.0/5
[2018/1/13 0:0:43] DEBUG-3: tun_rm_fwd_from_entry: Removing all the forwading entries association with the EID 136.0.0.0/5
[2018/1/13 0:0:43] DEBUG: tun_rm_fwd_from_entry: Entry 136.0.0.0/5 not found in the shasht!
[2018/1/13 0:0:43] DEBUG-3: pt_remove_ip_addr: Unable to locate cache entry 136.0.0.0/5 for deletion
Assertion failed: entry (lib/map_cache_entry.c: mcache_entry_del: 64)
Aborted
```

**Comment by albert-lopez** [comment] 2018-01-15 14:26
We found this issue some weeks ago and we think it is fixed in the testing branch. Could you have a try and let me know? Thanks

**Closed as completed** 2019-04-24 09:30 UTC
